server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://<username>:<password>@<host>:<port>/MCMD?authSource=admin
#      uri: mongodb://<username>:<password>@<host>:<port>/MCMD?authSource=admin
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# 腾讯云COS配置
tencent:
  cos:
    secret-id: <your-secret-id>  # 从腾讯云控制台获取
    secret-key: <your-secret-key>  # 从腾讯云控制台获取
    bucket-name: <your-bucket-name>  # 替换为你的存储桶名称
    region: <your-region>  # 替换为你的存储桶所在地域
    domain: <your-cos-domain>  # 替换为你的存储桶访问域名

# CORS配置
cors:
  allowed-origins: http://localhost:8080
#  allowed-origins: http://127.0.0.1
  # 在生产环境中，请替换为实际的前端域名，例如：
  # allowed-origins: https://your-frontend-domain.com,https://www.your-frontend-domain.com

# Cookie配置
cookie:
  secure: false  # 开发环境设置为false，生产环境应设置为true
  domain:        # 留空表示使用当前域名
  # 在生产环境中，应设置为实际的域名，例如：
  # domain: your-domain.com
